
flowchart LR
  O["<b>Optimisation</b><br/>fit the training data<br/>as well as possible"]
  G["<b>Generalisation</b><br/>perform on data<br/>never seen before"]
  M["The model"]
  O -- "you control this" --> M
  G -. "you do NOT control this" .-> M
