
flowchart TB
  C["An amorphous soup<br/>of complexity"]
  M["<b>Modularity</b><br/>split it into modules"]
  H["<b>Hierarchy</b><br/>organise the modules"]
  R["<b>Reuse</b><br/>use the same module<br/>in several places"]
  S["A system you can<br/>reason about"]
  C --> M --> H --> R --> S
